// <auto-generated />
namespace Chronozoom.Entities
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProgressiveLoad_TimelineSubtreeQuerySProc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProgressiveLoad_TimelineSubtreeQuerySProc));
        
        string IMigrationMetadata.Id
        {
            get { return "201306280528155_ProgressiveLoad_TimelineSubtreeQuerySProc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
